app/urls.py
from django.urls import path
from .views import upload_file, files, main

urlpatterns = [
    path('', main, name='main'),
    path('upload/', upload_file, name='upload'),
    path('files/', files, name='files'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name="Название категории")

    def __str__(self):
        return self.title


class File(models.Model):
    file = models.FileField(upload_to='files', verbose_name='Ваш файл')
    category = models.ForeignKey(
        Category, 
        models.CASCADE, 
        related_name='files', 
        verbose_name='Категория',
        null=True,
        blank=True
    )

    @property
    def file_name(self):
        return self.file.name.split('/')[-1]  # Возвращает только имя файла

    def __str__(self):
        return self.file.name

app/forms.py
from django import forms 
from .models import File, Category


class FileUploadForm(forms.Form):
    file = forms.FileField(required=True)
    category = forms.CharField(required=False)

    def save(self):
        instance = File()
        instance.file = self.cleaned_data['file']
        category_title = self.cleaned_data['category']
        if category_title:
            instance.category, created = Category.objects.get_or_create(title=category_title)
        
        instance.save()
        return instance

app/views.py
from django.http import FileResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import FileUploadForm
from .models import File, Category

def main(request):
    return redirect('files')

def upload_file(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save()
            return render(request, 'app/upload.html', {'file': file, 'categories': categories})
    else:
        form = FileUploadForm()

    return render(request, 'app/upload.html', {'form': form, 'categories': categories})

def files(request):
    categories = Category.objects.all()
    other_files = File.objects.filter(category__isnull=True)
    context = {
        'categories': categories,
        'other_files': other_files,
    }
    return render(request, 'app/files_list.html', context)

templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/base.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">File ExChange</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'files'  %}">Все файлы</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'upload' %}">Загрузить свои файлы</a>
              </li>
            </ul>
            <span class="navbar-text">
              Сервис для быстрого обмена файлами
            </span>
          </div>
        </div>
      </nav>


      {% block body %}{% endblock %}
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/app/files_list.html
{% extends 'app/base.html' %}

{% block body %}

  {% if categories or other_files %}
    {% for category in categories %}
      {% if category.files.all %}
        <h4>{{ category.title }}</h4>
        <div class="list">
          {% for file in category.files.all %}
          <p><a href="{{ file.file.url }}" download>{{ file.file_name }}</a></p>
          {% endfor %}
        </div>
      {% endif %}
    {% endfor %}

    {% if other_files %}
      <h4>Файлы без категории</h4>
      <div class="list">
        {% for file in other_files %}
          <p><a href="{{ file.file.url }}" download>{{ file.file_name }}</a></p>
        {% endfor %}
      </div>
    {% endif %}
  {% else %}
    <h3>Нет файлов</h3>
  {% endif %}

{% endblock %}

templates/app/upload.html
{% extends 'app/base.html' %}

{% block body %}
  {% if file %}
    <div class="alert alert-primary" role="alert">
      Файл {{ file.file_name }} был успешно добавлен
    </div>
  {% endif %}

  <form action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token  %}
    <p>
      <label for="id_file">Ваш файл:</label>
      <input id="id_file" type="file" class="form-control" name="file" required>
    </p>
    <p>
      <label for="id_category">Название категории</label>
      <input id="id_category" type="text" class="form-control" list="categories" name="category">
      <datalist id="categories">
        {% for category in categories %}
          <option value="{{ category.title }}">{{ category.title }}</option>
        {% endfor %}
      </datalist>
    </p>

    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
{% endblock %}